FROM maven:3-openjdk-18-slim AS build
WORKDIR /build
COPY pom.xml pom.xml
RUN mkdir data/ && mvn dependency:go-offline -B -Dmaven.repo.local=/mvn/.m2nrepo/repository
COPY src/ src/
RUN mvn package -f /build/pom.xml -DskipTests -Dmaven.repo.local=/mvn/.m2nrepo/repository
