---
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: maven
      image: maven:3.8.3-jdk-11-slim
      command: ['sleep', '99d']
      imagePullPolicy: Always
      tty: true

    - name: hadolint
      image: hadolint/hadolint:latest-debian
      imagePullPolicy: Always
      command:
        - cat
      tty: true
    
    - name: docker
      image: docker:20.10.12
      command: ['sleep', '99d']
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375

    - name: docker-daemon
      image: docker:20.10.12-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
